language: node_js
node_js:
  - "6"

env:
  global:
    # GITHUB_TOKEN (CD uses this to create releases)
    - secure: "bkkhEK+V3dqy4uxbrmamj+vFT3fUAMNdaTiBxJ3q0j+UJHgQEHojXiOuGTYtoqv8YMjgYFI6WZk7MRgOeZHg40vDsv+XUZg3Yhewnmlh1wWUlscN2swQAfYyZx0T2KyJT8Cu1cSTVFRhwpsG0sgyyWbw+rWGmzd2pfVYg0bH1sdX/bu7wF/i1RvPhhiXQdwzn0ZUOevN+E0L9I92wrPpm0cmNkk14+Yq1eHTICbbrfm1xwTJWGilmWGsKXrUVqLYHTSlEwkP7yPVih8yeQPCkM32j3A5gVckmwjJifUWbL9NJWKuOIDk5d1ZxJz28u82lZaf6CqiYOlxlLOSmWaHz2yququ2Kz9kaoitH/O2zcmwvD9r9NABAOHC/5SE1Hqf0ur/XxFQYZTaBZ7SkMnuGBNiWdCrp1Bx42TgSGmkUU+61YGdCOfAXb0BJfNHDqV4W6XHT5sm4EFDiYZFBG88XN8PckrLR4WBlseVioHC2fmC1qecqX41kf9U1CsxuzNMgOiGwvog14ZZAeTMuXNFbIzamHhQnRkR9wqSqIbIBuCpKUOjfkCXSg4TxWFThv/TLB95jQuYM6AcrHroD68F/6F1JZF8yPXDV/7QJbyNXTOxAVwv+lK/pmAhrESqrBWXsCP5142SehKN21QLV9sGVj6cYm3fr+cM9uDldfwUqcY="
    # NPM_AUTH_TOKEN (CD need it to use npm private registry)
    - secure: "cTyh0erqgd6YySv/kx3cN7gcOGx0eYE3PDloa+yQJbSxUQSBMDpkWGDTMVRCz+0x+sVlXxrzIJgHzhhJSwQKQVl2IS7lprEvzWOwkC2k8hcpfoE4cABEYIF3im405Nx3MpUwOCchnecE5L0JM39dYyi3ENSWVTrwr7CnDlb5dreRydzVTjnopORHjF/P90DUsT78Q6FkM99zEz6j56xUzhhLd9p4EfkVyl7+pVFbB+tWOYPy3OCsEc86d1lvZ5VOQLurVkO/zPZaIF9Bl9ED9AfUOMV40eD4UPzqgEtCyBiA49gcHSco5zTuq1rLyXQkn6Z56rplm9b7HnStwjNhUwmszJqwWlUiWn77gqFMYqWpl+Jyh0ftazlp+MecNedu+Be2Qw1KE2WBCdTCX7INlY207hpHM9+N54/p1k8l1/QuBNaPgi05KKWDsxkXMIuzIPqZDcFKubNK+eaND+1Ays+9EFsY8km2iwFn3d2UWgmkjVFU4UZ7VwlmlfF8fbtk6ARw89oWbK9kJrNP59llmYTM/bwQ/E2C7P7vRxZdwcsd3Du5ILVERT9t2EQBoDFnu/sUqU3kNWLLjlbutSmfa9y9GPsq58l1Od0vAnZLgsfCyJaQWE+Xjy80gvVHrnbo6uboVatnwkpf/LLnpK83N8FVjahPkPCBUJTFmCG6EVY=" 
    # NPM_REGISTRY_URL
    - secure: "UsP4JajBquU7bWzNiMydSUee5V6lKijFZwE1VcBQGiVRxxYluahrtiOhieVAYsURtCAm0VDzpOV374l5uAvEooBAoTSDaSaFRNWw2+NdkxvpL04cJBSQNhYWr+vFQSi/IfboSNdOn5IxhKm7iDJ3xgbfP12Yrhj5HhRY4xHSGaUD5Utc3XEhgxEwm4As8Udvo6pAX//kJXZXrrVU5QchUqYlLbvcqbv6QfDsA8HtG+ToaN5U1ZZR3KVSEZ4a3pNkPbKoNICFlsFvPiyw2sApzYtXHQowVhFKvhVIHI7HSR6vVJXyaL5ormXsBe1r2gIEyb2HR+yQSOB1VtIwHu9KFUDZiRXyQzKlTPvL5m30+nmWtA6dY9gN+KR5JSsv0N7FT7OJ6R1tC8jI7qw7Bljj2YaCYuQG0tomGurPNwyeTFWnjX2OCctt+sfxp1MJx2b8/yEyhRWoUet1Hm+7l8x5+f6VlTbifbuesnGy48lMw/Pva6F8vKOcL/fG+CIJQFkZdZq3oGW+GeBRa+QSva8xzKkUoydzCsBaFTq4JM4/1lLcB3i7y6QIf4JLfDQyPannB1nrcDNtKqk5A3W2uyR3NIV87EsuBdhlZeACNvawONTE+bSG+7N1A8swoUTXNVJJ2tuc6z+GpOCzlwtmIg9qvsZibBL9kjr3xvz8zlze6oU="

install:
  - echo ok

script:
  - echo ok

before_deploy:
  - .travis/create_npmrc.sh

deploy:
  - provider: script
    script: ".travis/release.sh release"
    skip_cleanup: true
    on:
      branch: master 

  - provider: script
    script: ".travis/release.sh dev"
    skip_cleanup: true
    on:
      branch: dev
